keys:
  - &nixos-ci age1mzmmyzey6lyt83pruhepm8t9vrxezyz736nxa49sxcrtkp4shvaszwj2vs
  - &nixos-n8n age19hn3w0k807przyrqcdnskaejr3h0ng4d36weyx42wzqce5yqvytqlkp0c9
  - &nixos-postgresql age18qp8rzf59tclrmka6jwsu0z3v9r7hsgjsrpg3tfg3rsfwnvhv5hskegs2d
  - &nixos-n8n-runner age1x43jzqgxx5969f4z5w287qmr5ntluez7s04k4g0ghgpn3r923v9qlfpwa2
  - &nixos-hindsight age1e6y94sum7gw528fcgcrctz77w0z6uymahsvr720av50vuvyd3ceq4a92f5
  - &nixos-calibre-wa age1swu597lg7m8n2tttwjweppqs48tef0c6j5rzcxjekd2d7vx2svlqskda8y
creation_rules:
  - path_regex: hosts/nixos-ci/secrets.yaml$
    key_groups:
      - age:
        - *nixos-ci
  - path_regex: hosts/nixos-n8n/secrets.yaml$
    key_groups:
      - age:
        - *nixos-ci
        - *nixos-n8n
  - path_regex: hosts/nixos-n8n-runner/secrets/auth-env.yaml$
    key_groups:
      - age:
        - *nixos-ci
        - *nixos-n8n-runner
  - path_regex: common/secrets/postgresql-shared.yaml$
    key_groups:
      - age:
        - *nixos-ci
        - *nixos-n8n
        - *nixos-hindsight
        - *nixos-postgresql
  - path_regex: hosts/nixos-hindsight/secrets/hindsight-env.env$
    key_groups:
      - age:
        - *nixos-ci
        - *nixos-hindsight
  - path_regex: hosts/nixos-calibre-wa/secrets/calibre-wa.yaml$
    key_groups:
      - age:
        - *nixos-ci
        - *nixos-calibre-wa
